Suppress -Wformat
external/zopfli/src/zopfli/cache.c:37:9: error: format specifies type 'unsigned long' but the argument has type 'size_t' (aka 'unsigned long long') [-Werror,-Wformat]

Upstream repo seems to no longer be maintained. Suppressing locally
to unblock the r596125 update.

Bug: 472333761
Test: presubmit
Change-Id: If8d81f15a1ac32edde3b54aa202fd804c11783fd